# Use the httpd-parent image as base
FROM quay.io/redhattraining/httpd-parent



EXPOSE 8080

LABEL io.kubernetes.name="my new name" \
      io.kubernetes.description="my new description" \
      io.openshift.expose-services="8080:http" \
      io.openshift.tags="httpd"

RUN sed -i "s/Listen 80/Listen 8080/g" /etc/httpd/conf/httpd.conf

RUN chgrp -R 0 /var/log/httpd /var/run/httpd && \
    chmod -r g=u /var/log/httpd /var/run/httpd

USER 1001


